### ISSUE TITLE
Add nudge for help in each "get started" article

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#156]
@dcossyleon 

We were thinking it would be nice to give a bit of a stronger prompt in the "Get Started" articles to clicking on the `HELP` link to find out about reprexes, etc. I think the best place to add is in the left sidebar under the menu for single articles only (i.e., not on the listing page with the welcome notice). 

This is just a mockup to show you what I am thinking, and I trust that you can style this WAY better, but I was leaning a bit away from pink on this one 🌸 

Here is a nice icon from the same author we already give attribution to:
https://www.flaticon.com/free-icon/customer-service_2103522

<img width="1364" alt="Screen Shot 2020-05-09 at 8 07 09 AM" src="https://user-images.githubusercontent.com/12160301/81477554-3020ca80-91cd-11ea-8939-91ec3c808a4e.png">

If you can style it, I think I can insert it somewhere. It might be a shortcode that we insert as a partial.

**Comment by dcossyleon** [comment]
I like this idea! What do you think of the version below?

![image](https://user-images.githubusercontent.com/29008894/81636481-faa0fa80-93e1-11ea-815c-be9e5cc6327b.png)

Or, I think we can even go smaller if we cut some of the text so that it stays on two lines: 
![image](https://user-images.githubusercontent.com/29008894/81636759-9cc0e280-93e2-11ea-8756-4d79b7f27f4c.png)

**Comment by apreshill** [comment]
I like this! I wonder if we could make it "Stuck? Confused? Ask for help." Then we can make the whole box clickable to the help page.

**Comment by topepo** [comment]
I like it. Operators are standing by 😄
