### ISSUE TITLE
textrecipes vignettes 

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/tidymodels.org-legacy#26]
textrecipes have started to get to a really good spot feature-wise lately. But looking at it the documentation, regarding examples and vignettes, has been lacking quite a bit. I'm planning to deal with those shortcomings the next month or so.

What are the guidelines of where they should be placed? Should I keep them in the textrecipes pkgdown or should I be prepared to have them here? 😄

**Comment by topepo** [comment]
Paging @juliasilge and @apreshill ...

Since it is in the tidymodels GH org, you could move/add them to there. 

We are in the process of trying to consolidate  data-analysis articles there. 

What that means, if you have a vignette that is focused on some technical aspect of the package and it does not have a significant data analysis component, keep it on the pkgdown site. Otherwise, move it to tidymodels.org. 

For example, the articles on [acquisition functions](https://tidymodels.github.io/tune/articles/acquisition_functions.html) and [parallel processing](https://tidymodels.github.io/tune/articles/extras/optimizations.html) will stay on the `tune` site but the others will move over.  

How long do they take to run? We'll use GH actions to build the site using CRAN packages. We have some extra time for the build (compared to travis) but want to make sure it works pretty smoothly.
