### ISSUE TITLE
tidyverse.org f/b on "learn" section

### ISSUE THREAD

**Issue by apreshill** [tidymodels/tidymodels.org-legacy#34]
Try changing list layout to group by category ("task") instead of level

- [ ] Add level as a taxonomy tag

- [x] Maybe: add numbering to the package taxonomy

- [x]  Add "back to top" buttons

- [ ] Deactivate paginator

also see issue #18

**Comment by topepo** [comment]
My notes: 

 * Look at SO and RS Community posts for tidymodels and try to organize in a way that would help existing questions. 

 * List all articles in a searchable way (Ctrl-F'able)

* Developer as a category (like "model tuning" or "pre processing")

* Have some way of saying how uncertain/unstable a package is/

* `noindex` some articles if needed

**Comment by apreshill** [comment]
(can you say more about the `noindex` thing? I know what it is generally, but not sure I follow how it applies here?)

**Comment by juliasilge** [comment]
Max and I just had our 1-on-1, and we said again how happy we are with the work on this so far. It is looking fantastic. 🙌 

Some questions we had, to discuss Thursday:

- Is a search feature possible / doable?
- Add a link to articles report broken code (ideally this link would **not** encourage getting help via this channel)
- We talked a lot about the "learn" section and possible ways to go. We wanted to float the possibility of A/B testing two versions, since there's a lot we don't know about how people will use this. This is possible in Netlify for certain paid accounts (send half your traffic to one branch, half to another, typically) but possibly is too big a project.

**Comment by apreshill** [comment]
1) Search is an ongoing struggle. We'll need to hire out a Hugo developer to integrate into the theme as I haven't had success with the free options. Sarah Lin and I are talking about Swiftype, which is easy to integrate but 💸 . Having said that, good organization can get you [pretty far](https://education.rstudio.com/blog/2019/12/making-your-stuff-findable/).

2) Ok

3) Possibly the one Netlify feature I haven't heard of! One low cost way to do something similar is use 2 different branch deploys, then use a survey to collect targeted feedback? With general user traffic (w/o a survey), I'm not sure what our metrics for success or decision-making would be?
